# Generated by Django 3.2.8 on 2021-10-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0002_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_id', models.IntegerField(editable=False)),
                ('connected_post_id', models.IntegerField(editable=False)),
                ('content', models.CharField(max_length=2000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('content', models.CharField(max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='post_pics')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('publisher_id', models.IntegerField(editable=False)),
                ('status', models.CharField(choices=[('Draft', 'Published')], max_length=20)),
            ],
        ),
    ]
