# Generated by Django 3.2.8 on 2021-10-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0003_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Published')], default='Draft', max_length=20),
        ),
    ]
