# Generated by Django 3.2.8 on 2021-10-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0010_alter_post_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('', 'Draft'), ('', 'Published')], max_length=30),
        ),
    ]
