# Generated by Django 3.2.8 on 2021-10-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0011_auto_20211031_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Published')], max_length=30),
        ),
    ]
