# Generated by Django 3.2.8 on 2021-10-31 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0015_alter_post_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='connected_post_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='poster_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='connected_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BLOG.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='My bio', max_length=2000),
        ),
    ]
