# Generated by Django 3.2.8 on 2021-10-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0017_alter_comment_connected_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Software Engineering'), ('2', 'Comedy'), ('3', 'News'), ('4', 'Informative')], default=('5', 'Personal'), max_length=30),
        ),
    ]
