# Generated by Django 3.2.8 on 2021-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0021_auto_20211031_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profile_pics'),
        ),
    ]
