# Generated by Django 3.2.8 on 2021-11-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0034_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_pics/default_post.png', upload_to='post_pics'),
        ),
    ]
